### ISSUE TITLE
Listitem Count Per Page建议不设置固定(<=100)

### ISSUE THREAD

**Issue by Arylo** [BoxSystem/StoreBox-Api#21]

**Comment by Arylo** [comment]
link cb48dc75dd24eda1ea92458f71e49546c0f4279e

**Comment by yanqing6628780** [comment]
perNum设置成10返回以下错误
{"statusCode":400,"error":"Bad Request","message":"Params Validation failed"}

![image](https://user-images.githubusercontent.com/8479740/35720149-6f101336-0827-11e8-9d18-956da75b4c1a.png)
